config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :recipes do

    get "search", on: :collection

    member do
      post 'favorite'
      delete 'favorite', to: 'recipes#unfavorite', as: 'unfavorite'
      post 'share'
    end
  end

  resources :cuisines, only: [:show, :new, :create]
  resources :recipe_types, only: [:show, :new, :create]
  resources :users, only: [:show, :edit, :update, :index] do
  get 'recipes'
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :user
  has_many :favorites
  validates :title,
            :recipe_type,
            :difficulty,
            :cook_time,
            :ingredients, :method,
            :cuisine_id, presence: true
  has_attached_file :image, styles: { default: '500x300' }
  validates_attachment_content_type :image, content_type: ['image/jpg',
                                                           'image/jpeg',
                                                           'image/png',
                                                           'image/gif']
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
  has_many :favorites
  has_many :favorite_recipes, through: :favorites, source: :recipe
  def favorite?(recipe)
    favorite_recipes.include?(recipe)
  end

  def owner?(recipe)
    email == recipe.user.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def new
    @cuisines = Cuisine.new
  end

  def show
    @cuisines = Cuisine.find params[:id]
    @recipes = Recipe.where(cuisine_id: params[:id])
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:name))
    if @cuisine.save
      redirect_to @cuisine
    else
      render '_error_messages'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
    favorites = Favorite.group(:recipe_id).count.sort_by { |_k, v| v }
                        .reverse.to_h
    favorites_array = []
    favorites.each_entry do |k, _v|
      favorites_array << Recipe.find(k)
    end
    @favorites = favorites_array.first(3)
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
      redirect_to @recipe_type
    else
      render '_error_messages'
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update]
  before_action :set_recipe, only: [:show, :edit, :update, :favorite,
                                    :unfavorite, :destroy, :share]
  before_action :set_cuisines, only: [:new, :edit, :update]
  before_action :set_recipe_types, only: [:new, :edit, :update]
  before_action :owner, only: [:edit]

  def show; end

  def destroy
    @recipe.destroy
    redirect_to root_path
    flash[:notice] = 'Receita removida com sucesso'
  end

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      set_cuisines
      set_recipe_types
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :new
    end
  end

  def favorite
    @favorite = Favorite.create(user: current_user, recipe: @recipe)
    redirect_to @recipe
    flash[:notice] = 'Receita adicionada como favorita'
  end

  def unfavorite
    @favorite = Favorite.find_by(user: current_user, recipe: @recipe)
    @favorite.destroy
    redirect_to @recipe
    flash[:notice] = 'Receita removida como favorita'
  end

  def search
    @search = params[:q]
    @recipes = Recipe.where('title LIKE ? OR ingredients LIKE ?',
                            "%#{@search}%", "%#{@search}%")
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  def share
    email = params[:email]
    message = params[:message]
    RecipesMailer.share(email, message, @recipe.id).deliver_now
    flash[:notice] = "Receita enviada para #{email}"
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title,
                                   :recipe_type_id,
                                   :cuisine_id, :difficulty,
                                   :cook_time, :ingredients, :method,
                                   :user_id, :image)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_cuisines
    @cuisines = Cuisine.all
  end

  def set_recipe_types
    @recipe_types = RecipeType.all
  end

  def owner
    @recipe = Recipe.find(params[:id])
    redirect_to root_path unless current_user.owner?(@recipe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def recipes
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/_error_messages.html.erb
<h3>Você deve informar o nome da cozinha</h3>
<%= link_to 'Voltar', new_recipe_path %>

app/views/cuisines/_form.html.erb
<%= form_for(@cuisines) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar'  %>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisines.name%></h1>

<% if @recipes.size != 0 %>
  <% @recipes.each do |recipe| %>
    <h1><%= recipe.title%></h1>
    <ul>
      <li><%= recipe.recipe_type.name%></li>
      <li><%= recipe.cuisine.name%></li>
      <li><%= recipe.difficulty%></li>
      <li><%= recipe.cook_time%> minutos</li>
    </ul>
  <% end %>
<% else %>
 <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>

app/views/home/index.html.erb
<h1> CookBook </h1>

<p><%= I18n.translate('site_description') %></p>
<%= form_tag("recipes/search", method: "get") do %>
  <%= text_field_tag(:q, nil, placeholder: "Busca") %>
  <%= submit_tag("Buscar") %>
<% end %>


<h1> Cozinhas </h1>
<% @cuisines.each do |cuisine| %>
<ul>
  <li><b><%= link_to(cuisine.name, cuisine_path(cuisine.id)) %></b></li>
</ul>
<% end %>

<h1> Tipos de receita </h1>
<% @recipe_types.each do |recipe_type| %>
<ul>
  <li><b><%= link_to(recipe_type.name, recipe_type_path(recipe_type.id)) %></b></li>
</ul>
<% end %>

<h1> Receitas </h1>
<% @recipes.each do |recipe| %>
      <h2><%= link_to recipe.title, recipe %></h2>
      <ul>
        <li><%= recipe.recipe_type.name %></li>
        <li><%= recipe.cuisine.name %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time %> minutos</li>
      </ul>
<% end %>
<h1>Receitas mais favoritadas</h1>
<% @favorites.each do |recipe| %>
    <%= render recipe %>
<% end %>

<%=link_to('Ver todas receitas', recipes_path)%>
<%=link_to('Enviar uma receita', new_recipe_path)%>

app/views/home/search.html.erb
<%if @recipes.empty?%>
  <p>Nenhuma receita encontrada</p>
<%else%>
  <% @recipes.each do |recipe| %>
    <%= render recipe%>
  <% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%if user_signed_in?%>
        <h3><%= "Bem vindo #{current_user.email}"%></h3></br>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete%>
      <%else%>
      <%=link_to 'Entrar', new_user_session_path%>
      <%end%>
      <%if flash[:notice]%>
        <%=flash[:notice]%>
      <%end%>
      <%if flash[:alert]%>
        <%=flash[:alert]%>
      <%end%>
      <%= yield %>
    </main>
    <aside>
      <%= yield :aside %>
    </aside>
  </body>
</html>

app/views/layouts/new.html.erb
<h1>Novo pedido</h1>

<% @categories.each do |cat| %>

  <%= link_to cat.name, customer_orders_path(category_id: cat.id, ), method: :post %>

<% end %>

app/views/partials/_cuisine_and_recipe_type.html.erb
<!-- menu Start -->
<div class="menu padd">
  <div class="container">
    <!-- Menu content container -->
    <div class="menu-container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4 col-sm-4">
          <!-- Menu header -->
          <div class="menu-head">
            <!-- Image for menu item -->
            <img class="menu-img img-responsive img-thumbnail" src="/img/menu/menu1.jpg" alt="" />
            <!-- Menu title / Heading -->
            <h3>Cozinhas</h3>
            <!-- Border for above heading -->
            <div class="title-border br-red"></div>
          </div>
          <!-- Menu item details -->
          <div class="menu-details br-red">
            <!-- Menu list -->
            <ul class="list-unstyled">
              <% @cuisines.each do |cuisine| %>
              <li>
                <div class="menu-list-item">
                  <!-- Icon -->
                  <i class="fa fa-angle-right"></i><%= link_to cuisine.name, cuisine_path(cuisine.id) %>
                </div>
                <% end %>
              </li>
            </ul>
          </div><!-- / Menu details end -->
        </div>
        <div class="col-md-4 col-sm-4">
          <!-- Menu header -->
          <div class="menu-head">
            <!-- Image for menu item -->
            <img class="menu-img img-responsive img-thumbnail" src="/img/menu/menu2.jpg" alt="" />
            <!-- Menu title / Heading -->
            <h3>Tipos</h3>
            <!-- Border for above heading -->
            <div class="title-border br-green"></div>
          </div>
          <!-- Menu item details -->
          <div class="menu-details br-green">
            <!-- Menu list -->
            <ul class="list-unstyled">
              <% @recipe_types.each do |recipe_type| %>
              <li>
                <div class="menu-list-item">
                  <!-- Icon -->
                  <i class="fa fa-angle-right"></i><%= link_to recipe_type.name, recipe_type_path(recipe_type.id) %>
                </div>
              </li>
              <% end %>
            </ul>
          </div><!-- / Menu details end -->
        </div>
        <div class="col-md-2"></div>
      </div>
    </div> <!-- /Menu container end -->
  </div>
</div>

app/views/partials/_search.html.erb
<div class="col-md-6 col-sm-12">
  <%= form_tag("/recipes/search", method: "get") do %>
    <div class="form-inline">
      <%= label_tag :busca, "Busca", class: ""  %>
      <%= text_field_tag :busca, nil, required: true,  class: "form-control" %>
      <%= submit_tag "Buscar" , class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/recipe_types/_error_messages.html.erb
<h3>Você deve informar o nome do tipo de receita</h3>
<%= link_to 'Voltar', new_recipe_type_path %>

app/views/recipe_types/_form.html.erb
<%= form_for(@recipe_type) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/new.html.erb
<%=render 'form'%>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% end %>
<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/_form.html.erb
<h1>Nova Receita</h1>
<% if flash[:error] %>
  <div class="error">
    <%= flash[:error] %>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
   <ul>
  </div>
<% end %>

<%=form_for(@recipe) do |f| %>
  <div>
    <%=f.label :title %>
    <%=f.text_field :title %>
  </div>

  <div>
    <%= f.label :recipe_type_id%>
    <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name  %>
  </div>

  <div>

    <%= f.label :cuisine_id %>
<%= f.collection_select :cuisine_id, @cuisines, :id, :name  %>
  </div>

  <div>
    <%=f.label :difficulty %>
    <%=f.text_field :difficulty %>
  </div>

  <div>
    <%=f.label :cook_time %>
    <%=f.text_field :cook_time %>
  </div>

  <div>
    <%=f.label :ingredients %>
    <%=f.text_field :ingredients %>
  </div>

  <div>
    <%=f.label :method %>
    <%=f.text_field :method %>
  </div>

  <div>
    <%= f.label :image ,'Imagem da Receita'%>
    <%= f.file_field :image %>
  </div>



  <%= f.submit('Enviar')%>
<%end%>

app/views/recipes/_options.html.erb
<% if user_signed_in?%>
  <% if current_user.favorite?(@recipe)%>
    <%=link_to 'Remover receita como favorita', unfavorite_recipe_path, method: :delete%>
  <% else %>
    <%=link_to 'Adicionar receita como favorita', favorite_recipe_path, method: :post %>
  <% end %>
  <% if current_user.owner?(@recipe) %>
    <%=link_to 'Editar', edit_recipe_path(@recipe)%>
    <%=link_to('Remover receita', recipe_path, method: :delete)%>
  <% end %>
<% end %>
<%=link_to('Voltar', root_path)%>

app/views/recipes/_recipe.html.erb
<h1><%= link_to(recipe.title, recipe) %></h1>
<ul>
  <li><%= recipe.recipe_type.name %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos</li>
</ul>

app/views/recipes/_send_form.html.erb
<h3>Envie para um amigo</h3>
<%= form_tag(share_recipe_path, method: :post) do  %>
  <%= label_tag :email, 'Email' %>
  <%= text_field_tag :email %>
  <%= label_tag :message, 'Mensagem' %>
  <%= text_area_tag :message %>
  <%= submit_tag 'Enviar' %>
<% end %>

app/views/recipes/_share_form.html.erb
<h3>Envie para um amigo</h3>
<%= form_tag(share_recipe_path, method: :post) do  %>
  <%= label_tag :email, 'Email' %>
  <%= text_field_tag :email %>
  <%= label_tag :message, 'Mensagem' %>
  <%= text_area_tag :message %>
  <%= submit_tag 'Enviar' %>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'form'%>

app/views/recipes/index.html.erb
<h1> Receitas </h1>
<% @recipes.each do |recipe| %>
      <h2><%= link_to recipe.title, recipe %></h2>
      <ul>
        <li><%= recipe.recipe_type.name %></li>
        <li><%= recipe.cuisine.name %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time %> minutos</li>
      </ul>
<% end %>

<%=link_to('Voltar', root_path)%>

app/views/recipes/new.html.erb
<%= render 'form'%>

app/views/recipes/show.html.erb
<h1><%=@recipe.title%></h1>

<h3>Detalhes</h3>

<b>Tipo da Receita:</b>
<p><%=@recipe.recipe_type.name%></p>

<b>Cozinha:</b>
<p><%=@recipe.cuisine.name%></p>

<b>Dificuldade:</b>
<p><%=@recipe.difficulty%></p>

<b>Tempo de preparo:</b>
<p><%=@recipe.cook_time%> minutos</p>

<h3>Ingredientes</h3>
<p><%=@recipe.ingredients%></p>

<h3>Como Preparar</h3>
<p><%=@recipe.method%></p>

<h3>Imagem da Receita</h3>
<img><%= image_tag @recipe.image.url(:medium) %><img>

<%= render 'options' %>
<%= render 'share_form' %>

app/views/users/recipes.html.erb
<h1>Receitas de <%= @user.name %></h1>

<% if @user.recipes.blank? %>
  <p>Esse usuário não possui receitas cadastradas</p>
<% else %>
  <% @user.recipes.each do |rec| %>
    <p><%= link_to rec.title, recipe_path(rec) %></p>
  <% end %>
<% end %>